#!/usr/bin/env python3
"""
syniq_pool_v1.py  --  Pool multiple SYN-IQ mapper CSVs into combined-n datasets.

WHAT IT DOES
  Takes any number of mapper_all_*.csv files (gradient runs and/or temp-by-temp
  runs), concatenates them, separates by temperature, renumbers runs so they
  never collide, and writes one CSV per temperature (n = pooled runs per
  question per agent).

WHY THE GUARDS
  Pooling is only valid when the rows were generated by the same process.
  This tool refuses to silently mix:
    - different DEPTHS in one cell (depth drives length/content)
    - different QUESTION SETS
    - for STEERED conditions, different HEADER-DELIVERY sides
      (tool version <=50 concatenates the header into the prompt;
       version >=51 sends it as a system message -- a measured seam).
      NATIVE is exempt: empty header => delivery-invariant => always poolable.
  It does NOT attempt to police cross-MODEL pooling (e.g. retired snapshots);
  it reports the source version/agent so you can judge.

USAGE
  python syniq_pool_v1.py file1.csv file2.csv ... [--outdir DIR] [--target-n N] [--cap]
  python syniq_pool_v1.py "/path/to/folder/*.csv"

OUTPUT
  <outdir>/pooled_<TEMPERATURE>.csv          one per temperature
  <outdir>/pool_report.txt                   the validity + n report
"""
import argparse, glob, os, re, sys, hashlib
import pandas as pd

KEY = ["agent", "temperature", "depth", "question_id"]   # one "cell" = unique combo
GROUP_FOR_OUTPUT = "temperature"

def parse_version(path):
    m = re.search(r"_V(\d+)", os.path.basename(path))
    return int(m.group(1)) if m else None

def delivery_side(version):
    if version is None: return "unknown"
    return "concat" if version <= 50 else "system"   # V51 moved header -> system message

def load_files(paths):
    frames = []
    for p in paths:
        df = pd.read_csv(p)
        df["__source_file"] = os.path.basename(p)
        v = parse_version(p)
        df["__source_version"] = v
        df["__delivery"] = delivery_side(v)
        frames.append(df)
    return pd.concat(frames, ignore_index=True)

def validate(df, report):
    ok = True
    # 1. depth consistency within each (agent,temperature)
    for (ag, tp), g in df.groupby(["agent", "temperature"]):
        depths = sorted(g["depth"].astype(str).unique())
        if len(depths) > 1:
            ok = False
            report.append(f"  [BLOCK] {ag}/{tp}: mixed depths {depths} -- depth drives content, do not pool.")
    # 2. question-set consistency within each (agent,temperature)
    for (ag, tp), g in df.groupby(["agent", "temperature"]):
        per_src = {s: frozenset(gs["question_id"].unique()) for s, gs in g.groupby("__source_file")}
        sets = set(per_src.values())
        if len(sets) > 1:
            ok = False
            report.append(f"  [BLOCK] {ag}/{tp}: question sets differ across sources {dict((k,len(v)) for k,v in per_src.items())}.")
    # 3. delivery-side consistency for STEERED conditions only
    for (ag, tp), g in df.groupby(["agent", "temperature"]):
        if str(tp).upper() == "NATIVE":
            continue  # delivery-invariant
        sides = sorted(g["__delivery"].unique())
        if len([s for s in sides if s != "unknown"]) > 1:
            ok = False
            report.append(f"  [BLOCK] {ag}/{tp}: mixes header-delivery sides {sides} "
                          f"(concat vs system) -- this is the measured version seam. Keep separate or use one side.")
        if "unknown" in sides:
            report.append(f"  [warn ] {ag}/{tp}: a source has no parseable version; cannot confirm delivery side.")
    # 4. exact-duplicate response detection (accidental double-include)
    h = df["response_text"].astype(str).map(lambda t: hashlib.md5(t.encode("utf-8","ignore")).hexdigest())
    dups = h.duplicated(keep=False)
    if dups.any():
        n = int(dups.sum())
        report.append(f"  [warn ] {n} rows share identical response_text with another row "
                      f"(possible double-included file or repeated draw). Inspect before trusting n.")
    return ok

def renumber(df):
    """Give each cell a clean pooled_run 1..k, preserving source order; keep original run as orig_run."""
    df = df.sort_values(KEY + ["__source_file", "run"]).copy()
    df["orig_run"] = df["run"]
    df["pooled_run"] = df.groupby(KEY).cumcount() + 1
    df["run"] = df["pooled_run"]
    return df

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("inputs", nargs="+", help="CSV paths or globs")
    ap.add_argument("--outdir", default="pooled_out")
    ap.add_argument("--target-n", type=int, default=50, help="expected runs/question/cell")
    ap.add_argument("--cap", action="store_true", help="truncate each cell to target-n")
    args = ap.parse_args()

    paths = []
    for x in args.inputs:
        paths.extend(sorted(glob.glob(x)) if any(c in x for c in "*?[") else [x])
    paths = [p for p in paths if os.path.exists(p)]
    if not paths:
        sys.exit("No input files found.")

    os.makedirs(args.outdir, exist_ok=True)
    df = load_files(paths)

    report = []
    report.append("SYN-IQ POOL REPORT")
    report.append(f"inputs ({len(paths)}): " + ", ".join(os.path.basename(p) for p in paths))
    report.append("")
    report.append("VALIDITY CHECKS")
    ok = validate(df, report)
    if all("[BLOCK]" not in line for line in report):
        report.append("  all clear -- no blocking confounds detected.")
    report.append("")

    df = renumber(df)
    if args.cap:
        df = df[df["pooled_run"] <= args.target_n]

    # n per cell report (collapsed across questions; show range if uneven)
    report.append(f"ACHIEVED n (runs per question) per agent x temperature   [target = {args.target_n}]")
    n_tbl = (df.groupby(KEY)["pooled_run"].max()
               .reset_index().rename(columns={"pooled_run": "n"}))
    agg = (n_tbl.groupby(["temperature", "agent"])["n"]
                 .agg(["min", "max"]).reset_index())
    for tp, g in agg.groupby("temperature"):
        report.append(f"  {tp}:")
        for _, r in g.iterrows():
            n_disp = f"{int(r['min'])}" if r["min"] == r["max"] else f"{int(r['min'])}-{int(r['max'])} (UNEVEN across questions!)"
            n_for_flag = int(r["min"])
            flag = "OK " if (r["min"] == r["max"] == args.target_n) else ("LOW" if r["max"] < args.target_n else (">N " if r["min"] > args.target_n else "CHK"))
            report.append(f"     [{flag}] {r['agent']:<8} n={n_disp}")
    report.append("")

    # provenance: which source contributed how much per cell
    report.append("PROVENANCE (rows per source x temperature x agent)")
    prov = (df.groupby(["temperature", "agent", "__source_version", "__source_file"]).size()
              .reset_index(name="rows"))
    for _, r in prov.iterrows():
        report.append(f"  {r['temperature']:<7} {r['agent']:<8} V{r['__source_version']}  "
                      f"{r['rows']:>4} rows  ({r['__source_file']})")
    report.append("")

    # write one CSV per temperature (drop helper cols except provenance)
    keep_helpers = ["orig_run", "__source_file", "__source_version", "__delivery"]
    written = []
    for tp, g in df.groupby("temperature"):
        out = os.path.join(args.outdir, f"pooled_{tp}.csv")
        g.drop(columns=["pooled_run"]).to_csv(out, index=False)
        written.append((tp, len(g), out))

    report.append("FILES WRITTEN")
    for tp, n, out in written:
        report.append(f"  {tp:<8} {n:>5} rows -> {out}")

    txt = "\n".join(report)
    with open(os.path.join(args.outdir, "pool_report.txt"), "w") as f:
        f.write(txt + "\n")
    print(txt)
    print("\n" + ("VALID: no blocking confounds." if ok else "WARNING: blocking confounds above -- fix before using."))

if __name__ == "__main__":
    main()
