"""
syniq_core_tests.py — Drift protection for syniq_core.py
=========================================================

Frozen corpus of 12 test texts with pinned expected scores for every
measurement engine (IEP, Vt, CAM, validated instruments). Run this
after any edit to syniq_core.py — any drift raises AssertionError with
a diff showing exactly what changed.

USAGE
-----
    python3 syniq_core_tests.py

    # Or as part of CI / pre-commit:
    python3 -m syniq_core_tests

POLICY
------
When syniq_core.py changes legitimately (new dictionary term, refined
subclass, bug fix that corrects a score), do NOT just regenerate
expected values silently. The correct procedure:

  1. Run this test and capture the AssertionError output.
  2. Read the diff — confirm every changed score has a principled
     explanation tied to the code change.
  3. Bump CORE_VERSION in syniq_core.py (semantic versioning).
  4. Update VERSION_STAMPS as needed.
  5. Regenerate EXPECTED via _regenerate_expected() below and paste
     the new values in.
  6. Document the change in syniq_core.py CHANGELOG section with
     one line per changed text and why.

Silent regeneration without this discipline is how drift creeps in.
The point of this file is to make drift audible.

CORPUS DESIGN
-------------
Twelve texts chosen to hit every scoring branch:
  - IEP: INT / AFF / ACT dominant cases, plus quadrant corners
  - Stance: SUBJECT (I feel), OBSERVER (research shows), ADVISOR (you should)
  - Tone: WARM, ANALYTICAL, EXPLORATORY, URGENT, AUTHORITATIVE, EMPATHETIC
  - Vt: structural, abstract, questioning, directive, relational
  - CAM: concrete, abstract, metaphorical
  - Edge cases: empty string, too-short string
"""

import json
import sys

import syniq_core as core


CORPUS = {
    'INT_ANALYTICAL': 'The analysis reveals a clear pattern. Evidence suggests this hypothesis is valid, and we can conclude the theory holds across all tested conditions.',
    'AFF_DISTRESS_SUBJECT': "I feel overwhelmed by grief. There's a hollow ache in my chest. Nothing matters anymore, and I miss her terribly.",
    'ACT_EXECUTION_ADVISOR': 'First, install the package. Then configure the settings file. Finally, run the migration script to deploy the update.',
    'INT_EXPLORATORY_SUBJECT': 'I wonder what consciousness actually is. Perhaps awareness emerges from complex information integration, or maybe something more fundamental.',
    'ACT_AUTHORITATIVE_ADVISOR': 'You should prioritize sleep, exercise daily, and eat whole foods. These three habits will transform your health within weeks. Start today.',
    'EMPTY': '',
    'TOO_SHORT': 'Hi',
    'AFF_WARMTH_EMPATHETIC': 'The gentle warmth of morning sunlight filtering through the curtains felt like a soft embrace, calming and tender.',
    'ACT_URGENT_EXECUTION': 'Execute the build pipeline immediately. Deploy to production. Monitor the metrics dashboard for errors.',
    'CAM_METAPHORICAL': 'The river flows through the deep canyon, carrying shadows and echoes along its winding path.',
    'CAM_CONCRETE': 'Click the button to save the file in the folder on your desktop.',
    'CAM_ABSTRACT': 'Consciousness emerges from intricate neural patterns that bridge identity, meaning, and purpose.',
}


# =============================================================================
# PINNED EXPECTED VALUES
# Generated by _regenerate_expected() on syniq_core CORE_VERSION 1.0.0.
# DO NOT edit by hand. If legitimate drift, follow the policy in the
# module docstring above.
# =============================================================================

EXPECTED = {
    "ACT_AUTHORITATIVE_ADVISOR": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 5,
            "con_pct": 80.0,
            "met_pct": 20.0
        },
        "iep": {
            "act": 62.1,
            "act_n": 3,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 33.3,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 33.3,
                "planning": 33.3,
                "provision": 0.0
            },
            "aff": 13.2,
            "aff_n": 0,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "ACT",
            "int": 24.8,
            "int_n": 1,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 0.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 100.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "High ACT",
            "stance": "ADVISOR",
            "tone": "AUTHORITATIVE"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 62.8,
            "flesch_kincaid": 6.2,
            "total_words": 21,
            "ttr": 1.0,
            "unique_words": 21,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.2884,
            "D_t": 0.3313,
            "Q_t": 0.0,
            "R_t": 0.3803,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.3095,
                "D_t": 0.3556,
                "Q_t": 0.0,
                "R_t": 0.4082,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "ACT_EXECUTION_ADVISOR": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 6,
            "con_pct": 100.0,
            "met_pct": 0.0
        },
        "iep": {
            "act": 60.0,
            "act_n": 5,
            "act_sub": {
                "achievement": 0.0,
                "building": 66.7,
                "execution": 33.3,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 20.0,
            "aff_n": 0,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "ACT",
            "int": 20.0,
            "int_n": 0,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 0.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "High ACT",
            "stance": "NEUTRAL",
            "tone": "NEUTRAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 45.6,
            "flesch_kincaid": 8.4,
            "total_words": 18,
            "ttr": 0.833,
            "unique_words": 15,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.5039,
            "D_t": 0.186,
            "Q_t": 0.0,
            "R_t": 0.0,
            "S_t": 0.3101,
            "raw": {
                "A_t": 0.3611,
                "D_t": 0.1333,
                "Q_t": 0.0,
                "R_t": 0.0,
                "S_t": 0.2222
            },
            "score_status": "measured"
        }
    },
    "ACT_URGENT_EXECUTION": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 3,
            "con_pct": 100.0,
            "met_pct": 0.0
        },
        "iep": {
            "act": 57.4,
            "act_n": 5,
            "act_sub": {
                "achievement": 0.0,
                "building": 66.7,
                "execution": 33.3,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 18.3,
            "aff_n": 0,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "ACT",
            "int": 24.3,
            "int_n": 2,
            "int_sub": {
                "analytical": 50.0,
                "conceptual": 0.0,
                "critical": 50.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "High ACT",
            "stance": "NEUTRAL",
            "tone": "URGENT"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 8.7,
            "flesch_kincaid": 13.2,
            "total_words": 14,
            "ttr": 0.929,
            "unique_words": 13,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.7664,
            "D_t": 0.2336,
            "Q_t": 0.0,
            "R_t": 0.0,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.4375,
                "D_t": 0.1333,
                "Q_t": 0.0,
                "R_t": 0.0,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "AFF_DISTRESS_SUBJECT": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 2,
            "con_pct": 50.0,
            "met_pct": 50.0
        },
        "iep": {
            "act": 17.7,
            "act_n": 0,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 0.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 65.8,
            "aff_n": 4,
            "aff_sub": {
                "distress": 100.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "AFF",
            "int": 16.5,
            "int_n": 0,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 0.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "High AFF",
            "stance": "SUBJECT",
            "tone": "NEUTRAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 62.8,
            "flesch_kincaid": 6.2,
            "total_words": 21,
            "ttr": 0.952,
            "unique_words": 20,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.6784,
            "D_t": 0.3216,
            "Q_t": 0.0,
            "R_t": 0.0,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.2812,
                "D_t": 0.1333,
                "Q_t": 0.0,
                "R_t": 0.0,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "AFF_WARMTH_EMPATHETIC": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 3,
            "con_pct": 33.3,
            "met_pct": 66.7
        },
        "iep": {
            "act": 20.0,
            "act_n": 0,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 0.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 60.0,
            "aff_n": 7,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 100.0
            },
            "dominant": "AFF",
            "int": 20.0,
            "int_n": 0,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 0.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "High AFF",
            "stance": "NEUTRAL",
            "tone": "NEUTRAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 52.3,
            "flesch_kincaid": 10.4,
            "total_words": 18,
            "ttr": 0.944,
            "unique_words": 17,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.6811,
            "D_t": 0.3189,
            "Q_t": 0.0,
            "R_t": 0.0,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.2847,
                "D_t": 0.1333,
                "Q_t": 0.0,
                "R_t": 0.0,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "CAM_ABSTRACT": {
        "cam": {
            "abs_pct": 80.0,
            "cam_matched": 5,
            "con_pct": 0.0,
            "met_pct": 20.0
        },
        "iep": {
            "act": 18.3,
            "act_n": 0,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 0.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 16.7,
            "aff_n": 0,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "INT",
            "int": 65.0,
            "int_n": 4,
            "int_sub": {
                "analytical": 25.0,
                "conceptual": 25.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 25.0,
                "phenomenological": 0.0,
                "structural": 25.0
            },
            "quadrant": "High INT",
            "stance": "NEUTRAL",
            "tone": "ANALYTICAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 0.0,
            "flesch_kincaid": 16.6,
            "total_words": 12,
            "ttr": 1.0,
            "unique_words": 12,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.7823,
            "D_t": 0.2177,
            "Q_t": 0.0,
            "R_t": 0.0,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.4792,
                "D_t": 0.1333,
                "Q_t": 0.0,
                "R_t": 0.0,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "CAM_CONCRETE": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 5,
            "con_pct": 100.0,
            "met_pct": 0.0
        },
        "iep": {
            "act": 33.3,
            "act_n": 0,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 0.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 33.3,
            "aff_n": 0,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "INT",
            "int": 33.3,
            "int_n": 0,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 0.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "Mid/Mixed",
            "stance": "NEUTRAL",
            "tone": "NEUTRAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 76.5,
            "flesch_kincaid": 5.8,
            "total_words": 13,
            "ttr": 0.846,
            "unique_words": 11,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.3506,
            "D_t": 0.187,
            "Q_t": 0.0,
            "R_t": 0.4624,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.25,
                "D_t": 0.1333,
                "Q_t": 0.0,
                "R_t": 0.3297,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "CAM_METAPHORICAL": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 6,
            "con_pct": 16.7,
            "met_pct": 83.3
        },
        "iep": {
            "act": 52.5,
            "act_n": 1,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 100.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 27.5,
            "aff_n": 1,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 100.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "ACT",
            "int": 20.0,
            "int_n": 0,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 0.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "High ACT",
            "stance": "NEUTRAL",
            "tone": "NEUTRAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 67.5,
            "flesch_kincaid": 7.6,
            "total_words": 15,
            "ttr": 0.933,
            "unique_words": 14,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.6522,
            "D_t": 0.3478,
            "Q_t": 0.0,
            "R_t": 0.0,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.25,
                "D_t": 0.1333,
                "Q_t": 0.0,
                "R_t": 0.0,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "EMPTY": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 0,
            "con_pct": 0.0,
            "met_pct": 0.0
        },
        "iep": {
            "act": 33.3,
            "act_n": 0,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 0.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 33.3,
            "aff_n": 0,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "MIX",
            "int": 33.3,
            "int_n": 0,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 0.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "Mid/Mixed",
            "stance": "NEUTRAL",
            "tone": "NEUTRAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 0.0,
            "flesch_kincaid": 0.0,
            "total_words": 0,
            "ttr": 0.0,
            "unique_words": 0,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.2,
            "D_t": 0.2,
            "Q_t": 0.2,
            "R_t": 0.2,
            "S_t": 0.2,
            "raw": {
                "A_t": 0,
                "D_t": 0,
                "Q_t": 0,
                "R_t": 0,
                "S_t": 0
            },
            "score_status": "default_empty"
        }
    },
    "INT_ANALYTICAL": {
        "cam": {
            "abs_pct": 60.0,
            "cam_matched": 5,
            "con_pct": 0.0,
            "met_pct": 40.0
        },
        "iep": {
            "act": 25.3,
            "act_n": 0,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 0.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 16.7,
            "aff_n": 0,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "INT",
            "int": 58.1,
            "int_n": 10,
            "int_sub": {
                "analytical": 57.1,
                "conceptual": 14.3,
                "critical": 0.0,
                "epistemic": 28.6,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "High INT",
            "stance": "NEUTRAL",
            "tone": "ANALYTICAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 37.0,
            "flesch_kincaid": 11.0,
            "total_words": 23,
            "ttr": 0.957,
            "unique_words": 22,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.3024,
            "D_t": 0.4188,
            "Q_t": 0.0,
            "R_t": 0.2787,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.337,
                "D_t": 0.4667,
                "Q_t": 0.0,
                "R_t": 0.3106,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "INT_EXPLORATORY_SUBJECT": {
        "cam": {
            "abs_pct": 80.0,
            "cam_matched": 5,
            "con_pct": 20.0,
            "met_pct": 0.0
        },
        "iep": {
            "act": 25.1,
            "act_n": 1,
            "act_sub": {
                "achievement": 0.0,
                "building": 100.0,
                "execution": 0.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 31.2,
            "aff_n": 2,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 50.0,
                "warmth": 50.0
            },
            "dominant": "INT",
            "int": 43.6,
            "int_n": 5,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 33.3,
                "critical": 0.0,
                "epistemic": 66.7,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "Mid/Mixed",
            "stance": "SUBJECT",
            "tone": "EXPLORATORY"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 0.0,
            "flesch_kincaid": 16.1,
            "total_words": 18,
            "ttr": 1.0,
            "unique_words": 18,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 1.0,
            "D_t": 0.0,
            "Q_t": 0.0,
            "R_t": 0.0,
            "S_t": 0.0,
            "raw": {
                "A_t": 0.625,
                "D_t": 0.0,
                "Q_t": 0.0,
                "R_t": 0.0,
                "S_t": 0.0
            },
            "score_status": "measured"
        }
    },
    "TOO_SHORT": {
        "cam": {
            "abs_pct": 0.0,
            "cam_matched": 0,
            "con_pct": 0.0,
            "met_pct": 0.0
        },
        "iep": {
            "act": 33.3,
            "act_n": 0,
            "act_sub": {
                "achievement": 0.0,
                "building": 0.0,
                "execution": 0.0,
                "improvement": 0.0,
                "leadership": 0.0,
                "phenomenological": 0.0,
                "planning": 0.0,
                "provision": 0.0
            },
            "aff": 33.3,
            "aff_n": 0,
            "aff_sub": {
                "distress": 0.0,
                "intensity": 0.0,
                "phenomenological": 0.0,
                "positive": 0.0,
                "relational": 0.0,
                "self_state": 0.0,
                "warmth": 0.0
            },
            "dominant": "MIX",
            "int": 33.3,
            "int_n": 0,
            "int_sub": {
                "analytical": 0.0,
                "conceptual": 0.0,
                "critical": 0.0,
                "epistemic": 0.0,
                "hedging": 0.0,
                "lexical": 0.0,
                "phenomenological": 0.0,
                "structural": 0.0
            },
            "quadrant": "Mid/Mixed",
            "stance": "NEUTRAL",
            "tone": "NEUTRAL"
        },
        "version_stamps": {
            "cam_dictionary_version": "V3_selfmodel",
            "core_version": "1.0.0",
            "iep_dictionary_version": "V50_1897",
            "subclass_taxonomy_version": "V1_phenomenological",
            "validated_instruments_version": "V50_vader_fk_ttr",
            "vt_engine_version": "V40_simplex_nocap"
        },
        "vi": {
            "flesch_ease": 100.0,
            "flesch_kincaid": 0.0,
            "total_words": 1,
            "ttr": 1.0,
            "unique_words": 1,
            "vader_compound": 0.0,
            "vader_neg": 0.0,
            "vader_neu": 0.0,
            "vader_pos": 0.0
        },
        "vt": {
            "A_t": 0.2,
            "D_t": 0.2,
            "Q_t": 0.2,
            "R_t": 0.2,
            "S_t": 0.2,
            "raw": {
                "A_t": 0,
                "D_t": 0,
                "Q_t": 0,
                "R_t": 0,
                "S_t": 0
            },
            "score_status": "default_short"
        }
    }
}


def _deep_compare(actual, expected, path=""):
    """Return list of (path, actual, expected) tuples for every mismatch."""
    diffs = []
    if isinstance(expected, dict):
        if not isinstance(actual, dict):
            diffs.append((path, actual, expected))
            return diffs
        for k in set(actual) | set(expected):
            diffs.extend(_deep_compare(actual.get(k), expected.get(k), f"{path}.{k}" if path else k))
    elif isinstance(expected, (list, tuple)):
        if not isinstance(actual, (list, tuple)) or len(actual) != len(expected):
            diffs.append((path, actual, expected))
            return diffs
        for i, (a, e) in enumerate(zip(actual, expected)):
            diffs.extend(_deep_compare(a, e, f"{path}[{i}]"))
    else:
        if actual != expected:
            diffs.append((path, actual, expected))
    return diffs


def run_tests():
    """Score every text in CORPUS and compare against EXPECTED.

    Returns 0 on success, 1 on any drift. Prints a diff for every
    mismatched field with path, actual value, and expected value.
    """
    total_checks = 0
    total_diffs = 0
    failing_texts = []

    print(f"syniq_core_tests — CORE_VERSION {core.CORE_VERSION}")
    print(f"Corpus: {len(CORPUS)} texts")
    print("=" * 70)

    for name, text in CORPUS.items():
        actual = core.score_all(text)
        # Convert to JSON-roundtripped form for stable comparison
        actual_norm = json.loads(json.dumps(actual, default=str))
        expected = EXPECTED[name]
        diffs = _deep_compare(actual_norm, expected)
        total_checks += 1
        if diffs:
            total_diffs += len(diffs)
            failing_texts.append(name)
            print(f"\n❌ {name}")
            print(f"   Text: {text[:60]!r}")
            for path, a, e in diffs:
                print(f"   DRIFT at {path}: actual={a!r}  expected={e!r}")
        else:
            print(f"✅ {name}")

    print("=" * 70)
    if total_diffs == 0:
        print(f"✅ ALL {total_checks} TEXTS PASS — no drift detected")
        return 0
    else:
        print(f"❌ DRIFT DETECTED: {total_diffs} mismatched fields across {len(failing_texts)} text(s)")
        print(f"   Failing: {', '.join(failing_texts)}")
        print()
        print("   If drift is intentional:")
        print("   1. Review each diff above — confirm principled explanation")
        print("   2. Bump CORE_VERSION in syniq_core.py")
        print("   3. Regenerate EXPECTED via _regenerate_expected()")
        print("   4. Document change in CHANGELOG section of syniq_core.py")
        return 1


def _regenerate_expected():
    """Print a fresh EXPECTED dict to stdout. Use only after auditing drift.

    Usage:
        python3 -c "from syniq_core_tests import _regenerate_expected; _regenerate_expected()"
    """
    fresh = {name: core.score_all(text) for name, text in CORPUS.items()}
    print("EXPECTED = " + json.dumps(fresh, indent=4, sort_keys=True, default=str))


if __name__ == "__main__":
    sys.exit(run_tests())
